Reintroduce npm test, so that travis runs gulp test
Since #296, we haven't been running any tests on travis, because travis is using `npm test` which "succeeds" with..

```
$ npm test

> manageiq-ui-service@1.0.1 test /home/travis/build/ManageIQ/manageiq-ui-service
> echo 'Error: no test specified'

Error: no test specified

The command "npm test" exited with 0.
```