More package lockdowns for s390x
Newer patch versions of these packages require es-abstract 1.22.1 which is
incompatible with yarn 1.22 on s390x

Error:
---> yarn run build␛[0m␛[0m
yarn run v1.22.18
$ yarn build:git-hash && NODE_ENV="production" webpack --bail --progress --profile --config config/webpack.prod.js
$ node config/githash.js
Successfully wrote Git hash - f07194ebaf9ff6c694230c970ac1b1b6c5f25519
[webpack-cli] Failed to load '/root/BUILD/manageiq-ui-service/config/webpack.prod.js' config
[webpack-cli] Error: Cannot find module 'es-abstract/2023/RequireObjectCoercible'
Require stack:
- /root/BUILD/manageiq-ui-service/node_modules/array.prototype.reduce/index.js
- /root/BUILD/manageiq-ui-service/node_modules/object.getownpropertydescriptors/implementation.js
- /root/BUILD/manageiq-ui-service/node_modules/object.getownpropertydescriptors/index.js
- /root/BUILD/manageiq-ui-service/node_modules/util.promisify/implementation.js
- /root/BUILD/manageiq-ui-service/node_modules/util.promisify/index.js
- /root/BUILD/manageiq-ui-service/node_modules/html-webpack-plugin/index.js
- /root/BUILD/manageiq-ui-service/config/webpack.prod.js
- /root/BUILD/manageiq-ui-service/node_modules/webpack-cli/lib/webpack-cli.js
- /root/BUILD/manageiq-ui-service/node_modules/webpack-cli/lib/bootstrap.js
- /root/BUILD/manageiq-ui-service/node_modules/webpack-cli/bin/cli.js
- /root/BUILD/manageiq-ui-service/node_modules/webpack/bin/webpack.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/root/BUILD/manageiq-ui-service/node_modules/array.prototype.reduce/index.js:4:30)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/BUILD/manageiq-ui-service/node_modules/array.prototype.reduce/index.js',
    '/root/BUILD/manageiq-ui-service/node_modules/object.getownpropertydescriptors/implementation.js',
    '/root/BUILD/manageiq-ui-service/node_modules/object.getownpropertydescriptors/index.js',
    '/root/BUILD/manageiq-ui-service/node_modules/util.promisify/implementation.js',
    '/root/BUILD/manageiq-ui-service/node_modules/util.promisify/index.js',
    '/root/BUILD/manageiq-ui-service/node_modules/html-webpack-plugin/index.js',
    '/root/BUILD/manageiq-ui-service/config/webpack.prod.js',
    '/root/BUILD/manageiq-ui-service/node_modules/webpack-cli/lib/webpack-cli.js',
    '/root/BUILD/manageiq-ui-service/node_modules/webpack-cli/lib/bootstrap.js',
    '/root/BUILD/manageiq-ui-service/node_modules/webpack-cli/bin/cli.js',
    '/root/BUILD/manageiq-ui-service/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 2.